//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRegister
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RetypePassword { get; set; }
        public string location { get; set; }
        public System.DateTime AccountCreateOn { get; set; }
        public string Role { get; set; }
    }
}
