//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetails
    {
        public string emp_id { get; set; }
        public string asset_id_sub { get; set; }
        public string asset_name { get; set; }
        public string serial_no { get; set; }
        public string ip_address { get; set; }
        public string mac_address { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
        public string Processor { get; set; }
        public Nullable<System.DateTime> Dateofissue { get; set; }
        public Nullable<System.DateTime> warranty_start { get; set; }
        public Nullable<System.DateTime> warranty_end { get; set; }
    }
}
