//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_us
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string mob { get; set; }
        public string query { get; set; }
        public int id { get; set; }
    }
}
