//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGmda
    {
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string DOB { get; set; }
        public string department { get; set; }
        public string designation { get; set; }
        public string DOJ { get; set; }
        public string permanent_Address { get; set; }
        public string official_email { get; set; }
    }
}
