//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterPumpAssetDetails
    {
        public int id { get; set; }
        public string location { get; set; }
        public string itemType { get; set; }
        public string category { get; set; }
        public string itemName { get; set; }
        public string pumphousename { get; set; }
        public string pumphouseWTP { get; set; }
        public string pumpreferencename { get; set; }
        public string retedpower { get; set; }
        public string reatedhead { get; set; }
        public string reatedflow { get; set; }
        public string typeofpump { get; set; }
        public string make { get; set; }
        public int Quantity { get; set; }
        public string UOM { get; set; }
        public string descript { get; set; }
    }
}
